### ISSUE TITLE
Z3  rom version 

### ISSUE THREAD

**Issue by phoenixshen** [ztc1997/HideableNavBar#1]
![screenshot_2015-09-23-11-11-05](https://cloud.githubusercontent.com/assets/1594534/10096082/5dfd4910-63a1-11e5-8a4c-ba917ef564de.jpg)
Hi,Ztc:
this tool is some pixels offset on some Z3 roms, just like the img shows, could u help to fix it ? i cound provide the test envirment for u!

**Comment by ztc1997** [comment]
The problem usually appears on phones which using GravityBox and enabled Navigation bar tweaks. If you aren't using GravityBox, it may caused by the ROM added some Navigation bar tweaks. Sorry but i can't compat all Roms include the Roms with special tweaks, i can only compat popular ROMs.

**Comment by phoenixshen** [comment]
I get that, and thanks u all the same.
