### ISSUE TITLE
MIUI V7 （4.4）For HUAWEI P7-L09 解析包错误。希望能适配4.4

### ISSUE THREAD

**Issue by KirinRyuuri** [ztc1997/HideableNavBar#5]
从Xposed上下载的最新的安装包。
确认文件无损坏。
提示“解析包时出现错误”

突然注意到只支持5.0以上的系统。
修改issue

**Comment by ztc1997** [comment]
无此打算，kitkat发布至今已有3年，项目是开源的，需要请自便
